### ISSUE TITLE
peer review (macOS)

### ISSUE THREAD

**Issue by jimmy1wu** [OpenLiberty/draft-guide-intellij#3]
Peer Review: review to be done by a peer member. 

- [x] Check that the guide has working instructions and sample code
- [x] Check the quality of code according to the best coding practices
- [x] Check the quality and presentation of guide according to [Structure and Style Guideline](https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles)
- [x] Check the consistency of guide with template and other guides
- [x] Examples with the right outcomes are provided
- [x] Example with the wrong outcomes, if any, are provided
- [x] Check that all licensing statements are properly stated in all files
- [x] Check that the `pom.xml`, `server.xml`, etc files are clean
- [x] Check that the directories are properly structured
- [ ] Test the guide on 3 platforms: Mac, Win, Linux
- [x] If any URL visits, try them on different browsers: Firefox, Chrome, Safari
- [x] If any URL visits, try `curl` command where applicable 
- [x] Ensure that the guide is using the latest version of the `liberty-maven-plugin` or `liberty-gradle-plugin` where applicable
- [x] Check that some of these `page-tags` are used in a guide: `MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud`. Only these tags are visible on the website. Latest list [here](https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_includes/visible-tags.liquid). 
- [x] Check the `attribution` statement is accurate for the guide
- [x] Verify the `travisTest.sh` script, if any, is accurate and consistent with other guides

Peer Testing: tests to be done by a peer member.

Guide’s contributor’s (if available, otherwise peer tester’s) responsibility: 
- [x] Additional tests where applicable: 
  - [x] Define test coverage and review with team (including guide contributor, if available)
  - [x] Define detail test cases 
  - [x] Consider corner cases targeting the specific guide
  - [ ] Consider different platform tests, ie, Mac, Windows, Linux
  - [x] Consider corner cases UI tests
  - [x] Consider testing URL on all browsers, ie, FF, Chrome, Safari
  - [x] Consider testing the `curl` command for URL visits
- [x] Consider building with both Maven and Gradle build tools 
- [x] Testing with different IDEs, ie, Atom, Eclipse (Optional: VS.code, IntelliJ, Microclimate)
- [x] Run Acrolinx Checker on draft (above 70 score approximately) **Score: 64**
- [x] Consider SEO title and description for the guides 
- [x] Ensure automated test is enable, set up with Travis CI, and able to schedule tests 
- [x] Run `diff -r start/ finish/` and there's no differences
- [ ] Ensure that the automation tests are able to run when PR is created

Peer Tester’s responsibility: 
- [x] Check the appearance of the guide on test site for the following items: 
  - [x] Table of contents 
  - [x] Headings
  - [x] Paragraphs
  - [x] code snippets
  - [x] outputs
  - [x] links
  - [x] hotspots
- [x] Test the guide end-to-end with working instruction and sample code
- [x] Perform all the defined test cases

**Comment by jimmy1wu** [comment]
**Title**
- [x] Using IntelliJ to develop microservice - > ... a microservice
- [x] Learn how to use IntelliJ IDE to develop microservice with Open Liberty.. -> Learn how to use the IntelliJ IDE to develop a microservice with Open Liberty.

**What you'll learn**
- [x] Not sure, but the space after the comma seems really big: `...computer software，by building a...`
- [x] The hyperlink on  `Creating a RESTful web service` leads to the `Creating the JAX-RS resource
 ` section of that guide instead of the top. Not sure if that is intentional.

**Additional prerequisites**
- [x] The J is not capitalized: `Intellij` (appears multiple times in this section)
- [x] `integrated development environment written in Java for developing computer software` was already stated in the previous section.
- [x] Learning basic setup and ... -> Learn basic setup and ...
- [x] Was this guide designed for `Community` edition or `Ultimate` edition? Does it matter?

**Getting started**

- [x] ~~`Get from Version Control` appears as `Check out from Version Control` for me.~~
- [x] ~~After clicking `Check out from Version Control` there is a dropdown, so it should mention to choose `Git` from the dropdown.~~
- [x] The `p` is not capitalized in `Import Project from external model` in my IDE
- [x] ~~`...and click on Finish`. `Finish` is not an option for me. The option to proceed is `Next` for me.~~
   - ~~There are a bunch of intermediate steps for me to setup the root directory, selecting the Maven projects to import, choosing the SDK, etc. before i get the `Finish` option.~~
- [x] ~~Not sure where this shows up `Click on Open on the welcome screen and navigate to the directory that the project was saved and select Ok. On the top left hand side of the screen, expand the guide-IntelliJ project.` When I finished configuring the project, the project opened in the root 
directory already.~~

**Configure the build project**
- [x] ~~`From the menu bar, select Run and click Edit Configurations`. The run button is disabled for me.~~
- [x] `...put Run finish` forgot a period at end of sentence.
- [x] What is the working directory for the `Stop finish` run config?

**Try what you'll build**
- [x] `You can also use the icons on the toolbar to toggle quickly between the different configurations that were set up above.` This might make more sense at the end of `Configure the build project` since this is where you create the configs.
- [x] What should the output be when i visit the url?

**Creating the application**
- [x] `Check out the service that you created at the http://localhost:9080/guide-IntelliJ/System/properties URL.` To me, it sounds like we are done and the URL is giving the same response as the one in `try what you'll build` even though we are in the creating section.
- [x] What should the output be when i visit the url?

**Configuring the server**
- [x] `To get the service running, the Open Liberty server needs to be correctly configured.` In the previous step, the URL seems to be working correctly though (i am getting the same  json response as the finish section except the url is `guide-IntelliJ/System/properties` instead of `/LibertyProject/System/properties`).

**Running the microservice**
- [x] What should the output be when i visit the url?

**Debugging the microservice**
- [x] 7777, Port and OK should be in quotes like: `7777`, etc.
- [x] `Type 7777 into the Port field and click OK to start the debugger.` The debugger did not start automatically for me.
- [x] `Open the class PropertiesResource in the editor and click in the margin on the first line of the method getProperties()`. Maybe use a hotspot to highlight the line i should add the breakpoint to.
- [x] `Click Resume Program to continue testing your application.` Resume Program is an icon button and not a text button. Maybe should point to where this button is and what it looks like.
- [x] `The server will stop at the breakpoint you set and you can examine the state of your JVM` The debugger just says `Variables -> this = {PropertiesResource@6887} Class has no fields`.

**Testing the microservice**
- [x] `This test class has more lines of code than the resource implementation.` What resource implementation?
- [x] `... or they can be written to call the application server directly.` Should mention that you need to press the return key to run the tests directly from dev mode.
- [x] What should the output be if it was a success?

**In general**
- [x] Maybe provide keyboard shortcuts to certain button commands. e.g. Instead of pressing on the Run button, you can press `Ctrl+R` on mac.
- [x] Copyright missing in pom.xml and server.xml files
- [x] Check that some of these page-tags are used in a guide: MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE, Security, Cloud. Only these tags are visible on the website. Latest list here.
    - You include IntelliJ in your page-tags which is not part of the list
- [x] Need `page-seo-title` and `page-seo-description`
- [x] Spacing differences in PropertiesResource, SystemApplication and EndpointIT files
- [x] Need to setup automated tests in TravisCI `https://travis-ci.org/OpenLiberty/draft-guide-intellij`

**Comment by jj-zhang** [comment]
> Was this guide designed for Community edition or Ultimate edition? Does it matter?

It doesn't matter

**Comment by jj-zhang** [comment]
> Get from Version Control appears as Check out from Version Control for me.

![image](https://user-images.githubusercontent.com/24790572/71750611-0898aa80-2e47-11ea-902b-9f0d4889697e.png)

This seems to work good for me.

**Comment by jimmy1wu** [comment]
> > Get from Version Control appears as Check out from Version Control for me.
> 
> ![image](https://user-images.githubusercontent.com/24790572/71750611-0898aa80-2e47-11ea-902b-9f0d4889697e.png)
> 
> This seems to work good for me.

I meant in the IDE

**Comment by jj-zhang** [comment]
> > > Get from Version Control appears as Check out from Version Control for me.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/24790572/71750611-0898aa80-2e47-11ea-902b-9f0d4889697e.png)
> > This seems to work good for me.
> 
> I meant in the IDE

![image](https://user-images.githubusercontent.com/24790572/71750980-13a00a80-2e48-11ea-8727-2f0a79bb865a.png)

Is this because of the IDE version? What's your IntelliJ version?

**Comment by jimmy1wu** [comment]
> > > > Get from Version Control appears as Check out from Version Control for me.
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/24790572/71750611-0898aa80-2e47-11ea-902b-9f0d4889697e.png)
> > > This seems to work good for me.
> > 
> > 
> > I meant in the IDE
> 
> ![image](https://user-images.githubusercontent.com/24790572/71750980-13a00a80-2e48-11ea-8727-2f0a79bb865a.png)
> 
> Is this because of the IDE version? What's your IntelliJ version?

This is the screen i get when i launch intellij
![image](https://user-images.githubusercontent.com/33457590/71751326-37b01b80-2e49-11ea-82c5-a734e67fc58b.png)

**Comment by jj-zhang** [comment]
> > > > > Get from Version Control appears as Check out from Version Control for me.
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/24790572/71750611-0898aa80-2e47-11ea-902b-9f0d4889697e.png)
> > > > This seems to work good for me.
> > > 
> > > 
> > > I meant in the IDE
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/24790572/71750980-13a00a80-2e48-11ea-8727-2f0a79bb865a.png)
> > Is this because of the IDE version? What's your IntelliJ version?
> 
> This is the screen i get when i launch intellij
> ![image](https://user-images.githubusercontent.com/33457590/71751326-37b01b80-2e49-11ea-82c5-a734e67fc58b.png)

![image](https://user-images.githubusercontent.com/24790572/71751377-629a6f80-2e49-11ea-9ada-525ff2c03e69.png)

It seems that we have different IntelliJ Version, I don't have the dropdown box as well.

**Comment by jimmy1wu** [comment]
> > > > > > Get from Version Control appears as Check out from Version Control for me.
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/24790572/71750611-0898aa80-2e47-11ea-902b-9f0d4889697e.png)
> > > > > This seems to work good for me.
> > > > 
> > > > 
> > > > I meant in the IDE
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/24790572/71750980-13a00a80-2e48-11ea-8727-2f0a79bb865a.png)
> > > Is this because of the IDE version? What's your IntelliJ version?
> > 
> > 
> > This is the screen i get when i launch intellij
> > ![image](https://user-images.githubusercontent.com/33457590/71751326-37b01b80-2e49-11ea-82c5-a734e67fc58b.png)
> 
> ![image](https://user-images.githubusercontent.com/24790572/71751377-629a6f80-2e49-11ea-9ada-525ff2c03e69.png)
> 
> It seems that we have different IntelliJ Version, I don't have the dropdown box as well.

Yours is newer, let's go with yours then

**Comment by jj-zhang** [comment]
> What is the working directory for the Stop finish run config?

It should be the directory of finish directory... I've mentioned it above.

![image](https://user-images.githubusercontent.com/24790572/71751669-4a772000-2e4a-11ea-8eb1-a0ca2665fe5b.png)

**Comment by jj-zhang** [comment]
> ...and click on Finish. Finish is not an option for me. The option to proceed is Next for me.
There are a bunch of intermediate steps for me to setup the root directory, selecting the Maven projects to import, choosing the SDK, etc. before i get the Finish option.

![image](https://user-images.githubusercontent.com/24790572/71751809-c709fe80-2e4a-11ea-8fc9-585be2f6a954.png)

It is `Finish` for me and there is no intermediate step. I believe IntelliJ's up-to-date version waive the intermediate step.

**Comment by jj-zhang** [comment]
>  Not sure where this shows up Click on Open on the welcome screen and navigate to the directory that the project was saved and select Ok. On the top left hand side of the screen, expand the guide-IntelliJ project. When I finished configuring the project, the project opened in the root
directory already.

Same as above, maybe the reason of this is that we have different version

**Comment by jj-zhang** [comment]
> From the menu bar, select Run and click Edit Configurations. The run button is disabled for me.

Can you provide a screenshot for that? It seems to work for me

**Comment by jimmy1wu** [comment]
Retrying using the latest version of intellij (2019.3.1)

**Comment by jimmy1wu** [comment]
After retrying using the latest version of intelliJ (2019.3.1), i crossed out some irrelevant comments in the last peer review comment above. In addition, i added some new comments here.

**Getting started**
- [x] `You should see a progress bar indicating the status of the operation.` This does not work since there is not pom.xml in the root dir.

**Configure the build project**
- [x] These steps should be split up since you need to import the start and finish projects independently

**Try what you’ll build**
- [x] Have to mention that you have to import the finish project as a maven project

**Creating the application**
- [x] Have to mention that you have to import the start project as a maven project

**In general**
- [x] Maybe include how to stop dev mode and/or terminate the `Develop start` task
- [x] Should prob mention the version of intellij this guide was made for since users are probably downloading the latest and things can change in the IDE

Unless there is a way to import both projects simultaneously in the getting started section, you might have to import them separately as stated in this feedback.

**Comment by jj-zhang** [comment]
>**Try what you’ll build**
Have to mention that you have to import the finish project as a maven project

>**Creating the application**
Have to mention that you have to import the start project as a maven project

It has mentioned in the `getting started` session.

![image](https://user-images.githubusercontent.com/24790572/72024390-4df01a00-3243-11ea-807b-ad154b54c6bf.png)

**Comment by jj-zhang** [comment]
> Maybe include how to stop dev mode and/or terminate the Develop start task

It has mentioned in the `Running the Test` section

![image](https://user-images.githubusercontent.com/24790572/72024618-c6ef7180-3243-11ea-9cc7-230a0e7d9577.png)

**Comment by jj-zhang** [comment]
> This test class has more lines of code than the resource implementation. What resource implementation?

I believe this is the src code, which is the core part of the application

**Comment by jj-zhang** [comment]
> What should the output be if it was a success?

![image](https://user-images.githubusercontent.com/24790572/72042798-709f2480-327d-11ea-8949-e849d0186152.png)

The successful output is indicated here.

**Comment by jj-zhang** [comment]
Some testing part of guide is hidden, now it's all showed up in the lgdev site.

**Comment by jj-zhang** [comment]
> To get the service running, the Open Liberty server needs to be correctly configured. In the previous step, the URL seems to be working correctly though (i am getting the same json response as the finish section except the url is guide-IntelliJ/System/properties instead of /LibertyProject/System/properties).

You are right, basically we're done... The output of the json file for `creating the application` is same as `Try what you'll build`.

**Comment by jimmy1wu** [comment]
> > **Try what you’ll build**
> > Have to mention that you have to import the finish project as a maven project
> 
> > **Creating the application**
> > Have to mention that you have to import the start project as a maven project
> 
> It has mentioned in the `getting started` session.
> 
> ![image](https://user-images.githubusercontent.com/24790572/72024390-4df01a00-3243-11ea-807b-ad154b54c6bf.png)

But when i import the project that way, it does not open anything since there is no pom.xml in the root folder. i had to import the start and finish individually to get the IDE to open.

**Comment by jimmy1wu** [comment]
> > To get the service running, the Open Liberty server needs to be correctly configured. In the previous step, the URL seems to be working correctly though (i am getting the same json response as the finish section except the url is guide-IntelliJ/System/properties instead of /LibertyProject/System/properties).
> 
> You are right, basically we're done... The output of the json file for `creating the application` is same as `Try what you'll build`.

I think `To get the service running` implies that it is not working before.

**Comment by jimmy1wu** [comment]
> > Maybe include how to stop dev mode and/or terminate the Develop start task
> 
> It has mentioned in the `Running the Test` section
> 
> ![image](https://user-images.githubusercontent.com/24790572/72024618-c6ef7180-3243-11ea-9cc7-230a0e7d9577.png)

That was only created for the finish directory. We are in the start directory when creating the application and running in dev mode.

**Comment by jj-zhang** [comment]
> > > Maybe include how to stop dev mode and/or terminate the Develop start task
> > 
> > 
> > It has mentioned in the `Running the Test` section
> > ![image](https://user-images.githubusercontent.com/24790572/72024618-c6ef7180-3243-11ea-9cc7-230a0e7d9577.png)
> 
> That was only created for the finish directory. We are in the start directory when creating the application and running in dev mode.

I've changed it from `stop finish` to `stop start`.

**Comment by jimmy1wu** [comment]
-- peer review after darren addressed my changes

- [x] `...screen and navigate to the directory that the project was saved and select Ok`. Mine says `Open` instead of `Ok`
<kbd>
<img width="431" alt="Screen Shot 2020-01-16 at 2 52 24 PM" src="https://user-images.githubusercontent.com/33457590/72558095-09323780-3870-11ea-9e42-15620d964ea2.png">
</kbd>

--

- [x] `On the upper left side of the screen, expand the guide-intellij project.` I think the name of what this is referring to is the `Project Tool Window`: https://www.jetbrains.com/help/idea/project-tool-window.html Maybe we should include that name in that sentence.

--

- [x] ` Select Maven in Add new configuration`. Maybe say `under` instead of `in` ?
<kbd>
<img width="177" alt="Screen Shot 2020-01-16 at 3 03 52 PM" src="https://user-images.githubusercontent.com/33457590/72558841-80b49680-3871-11ea-942d-eef1c02a2c1f.png">
</kbd>
 
--

- [x] I still get no context root found after replacing the server.xml file

--- cannot verify the rest of the guide until last comment is fixed ---

**Comment by jj-zhang** [comment]
>  I still get no context root found after replacing the server.xml file

It works for me.

**Comment by jj-zhang** [comment]
@jimmy1wu Addressed the feedback. Please check.

**Comment by jimmy1wu** [comment]
- [x] `Click in the margin on line 34, which is return System.getProperties();` line 34 is the `Properties props = System.getProperties()`line. Also, you are not using the props variable:

```
        Properties props = System.getProperties();
        return System.getProperties();
```
- [x] You should be using a hotspot instead of saying line 34...

- [x] `The server will stop at the breakpoint you set and you can examine the state of your JVM` This output does not seem correct.
![image](https://user-images.githubusercontent.com/33457590/72808486-a18d3b00-3c27-11ea-9e26-b591ce10d650.png)

- [x] `press enter/return key to run the...` you need to remove the breakpoint before this, otherwise it will break the test

**Comment by salmad3** [comment]
### Peer Review 2 on Windows
- Feedback I had addressed by Nimrah's peer review on Mac/Linux.
- End-to-end test completed.
