### ISSUE TITLE
Peer Review 2 - Mac/Linux

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/draft-guide-intellij#38]
### Getting started
- [x] Cloning section not clear. Am i supposed to clone with `git clone [URL]` or Intellij's cloning tool?
    - if using the terminal, then make sure the command box says 
`git clone https://github.com/OpenLiberty/guide-intellij.git`, instead of just the URL
- [x] the process is not in the same order as described in this sentence:
     > Start IntelliJ IDEA, select `Import Project`. On the `Import Project dialog box`, choose `Import project from external model` and navigate to the directory that the project was saved, select `Maven` and click `Finish`.
    - My order was: Click `Import Project`, then choose directory, then choose `Import project from external model`, then select `Maven`
    - On Mac, IntelliJ IDEA 2019.3.2 (Ultimate Edition)
- [x]  Another step might be needed after this sentence
    > Select `View` in the menu bar and navigate to `Tool Windows` and click `Project` to display the `Project Tool Window` at top left side. Expand the `guide-intellij` project.
    - to display the Project Tool Window properly and showing the subfolders and files in `draft-guide-intellij` repo, the `Project Files` option needs to be selected. Mine was automatically set on `Project` and doesn't display the subfolders like start and finish:
    ![image](https://user-images.githubusercontent.com/46586499/73755098-85af8c00-4733-11ea-856f-6d66cace5355.png)
    ![image](https://user-images.githubusercontent.com/46586499/73755119-8c3e0380-4733-11ea-942a-74cb77a26bb5.png)
    ![image](https://user-images.githubusercontent.com/46586499/73755134-92cc7b00-4733-11ea-8708-319a234baca3.png)

### Configuring the server
- [x] same `Project Files` point as above needs to be added to this part:
    > If the `Project Tool Window` is not currently displayed, select `View` in the menu bar and navigate to `Tool Windows` and click `Project` to display the `Project Tool Window` at top left side. Expand the `guide-intellij` project and navigate to the `start` directory to begin.
- [x] The hotspot `context root` isn't highlighting anything in the codepane:
    > The context root value `context root` is defined at the `pom.xml`.

### Debugging the microservice
- [x] `PropertiesResource` in the `start` directory actually has the line needed to be debugged 
(`return System.getProperties();`) on line `35`, not `34`. 
    > Click in the margin on line `34`. This action will set a breakpoint on that line.

    ![image](https://user-images.githubusercontent.com/46586499/73756040-f5724680-4734-11ea-8a79-8fd2fc793a69.png)

- [ ] Nothing is happening during the debug stage when ii click the URL:
    > Now refresh the browser at the http://localhost:9080/LibertyProject/System/properties URL. The server will stop at the breakpoint you set and you can examine the state of your JVM. 

### Testing the microservice
- [x] put file hotspot for `EndpointIT` here:
    > The test EndpointIT class is already provided for you to test the REST service.

**Comment by NimG98** [comment]
End-to-end test:

- **Mac** (DONE)
- **Linux** (DONE)

**Comment by jj-zhang** [comment]
> to display the Project Tool Window properly and showing the subfolders and files in draft-guide-intellij repo, the Project Files option needs to be selected. Mine was automatically set on Project and doesn't display the subfolders like start and finish:

This is what project looks like for me.

![image](https://user-images.githubusercontent.com/24790572/74007771-2200ab00-494d-11ea-9a8a-6047ae55c8ab.png)

**Comment by jj-zhang** [comment]
When I was testing it, I found out that it only works when you reopen the Intellij...

**Comment by NimG98** [comment]
Feedback addressed in https://github.com/OpenLiberty/draft-guide-intellij/pull/39/files

**Comment by NimG98** [comment]
Regarding new change (https://github.com/OpenLiberty/draft-guide-intellij/pull/39/files#diff-7bd4a925c695c2eb0eced3872b9b965fR57):
> Navigate to the directory that the project was saved and click `Open`.

Change to:
> Navigate to the directory **where** the project was saved and click `Open`.

**Comment by NimG98** [comment]
Regarding new change (https://github.com/OpenLiberty/draft-guide-intellij/pull/39/files#diff-7bd4a925c695c2eb0eced3872b9b965fR137):
> If there is no guide directory showed up in the top left side, try reopen the IntelliJ IDEA.

Change to:
> If there is no guide directory showed up in the top left side, try **to** re-open the IntelliJ IDEA.

**Comment by NimG98** [comment]
> - [ ] The hotspot `context root` isn't highlighting anything in the codepane:
>    > The context root value `context root` is defined at the `pom.xml`.

This still isn't addressed.

**Comment by NimG98** [comment]
feedback addressed - LGTM
